var mongoose = require("mongoose");
var Campground = require("./models/campground");
var Comment = require("./models/comment");

var data = [
  { name : "lamborghini_veneno_",
    image : "https://www.hdwallpapers.in/walls/lamborghini_veneno_sports_car-HD.jpg",
    description :  "<strong>LAMBORGHINI VENENO: IT WILL FEEL LIKE FLYING ON THE ROAD.</strong><p>The Lamborghini Veneno Roadster takes the aerodynamic efficiency of a racing prototype onto everyday roads. This super sports car is characterized by optimal aerodynamics in order to guarantee stability in fast curves and a behavior like a racing prototype. All of this on a car devised for the road. The perfect car for sports-driving lovers.</p> ",
    description1 : "<h2>DESIGN A MASTERPIECE OF POWER AND LIGHTNESS INSPIRED BY AERONAUTICS:</h2><p>Here are the technical specifications of the new Veneno: with a 6.5 liter aspirated V12 engine and a top speed of 355 km/h, this Lamborghini concept car represents state-of-the-art design inspired by aeronautics, capable of giving you the indescribable feeling of flying on the road. Faithful to the Lamborghini lines, the Veneno is characterized by extreme proportions, emerging in the forceful arrow-shaped front as well as alternating razor-sharp lines and sleek, tight surfaces.</p>",


    image1 : "https://images6.alphacoders.com/685/thumb-350-685698.jpg",
    image2 : "https://www.hdwallpapers.in/walls/lamborghini_veneno-wide.jpg",
    image3 : "http://www.chdwallpapers.com/web/wallpapers/lamborghini-veneno-hd/thumbnail/lg.jpg",
    image4 : "https://i.ytimg.com/vi/5nT1fNmILiU/maxresdefault.jpg",
    image5 : "https://www.ihdimages.com/wp-content/uploadsktz/2014/10/lamborghini_veneno_interior_wallpaper_free_desktop.jpg",
    image6 : "http://images.caricos.com/l/lamborghini/2013_lamborghini_veneno/images/1920x1080/2013_lamborghini_veneno_10_1920x1080.jpg",
    image7 : "https://s-media-cache-ak0.pinimg.com/originals/c0/62/79/c062799240b18e9f55ceb3b644c0f12b.jpg",
    image8 : "https://s-media-cache-ak0.pinimg.com/originals/74/fa/37/74fa37d5f26388a545c032895e969216.jpg",
    image9 : "http://www.lambocars.com/images/aventador/lamborghini_veneno_64.jpg",

    type : "V12, 60°, MPI (Multi Point Injection)",
    displacement : "6.498 cm³ (396.5 cu in)",
    borexstroke : "95 mm x 76,4 mm (3.74 x 3.01 in)",
    compression : "11,8:1",
    maxpower : "750 CV (552 kW) @ 8.400 rpm",
    maxtorque : "690 Nm (507 lb.-ft.) @ 5.500 rpm",
    transmissiontype : "Electronically controlled all-wheel drive system (Haldex gen. IV) with rear mechanical self-locking differential",
    gearbox : "ISR (Independent Shifting Rods) gearbox with 7 speeds",
    maxspeed :  "355 km/h (221 mph)",
    acceleration : "0-100 KM/H (0-62 MPH)2,9S",
    rimf : "FRONT20'' specific forged rims; 9J x 20 ET32.2",
    rimr : "REAR21'' specific forged rims; 13J x 21 ET66.7",
    tiref : "FRONT255/30 ZR20",
    tirer : "REAR355/25 ZR21"
  },

  { name : "Koenigsegg CCXR_",
    image : "http://hdfreewallpaper.net/wp-content/uploads/2015/08/Koenigsegg-CCXR-Trevita-2-free-hd-wallpapers.jpg",



    image1 : "http://www.hdcarwallpapers.com/walls/the_koenigsegg_trevita-wide.jpg",
    image2 : "http://celebritiesgallery.in/wp-content/uploads/2016/08/FunMozar-%E2%80%93-Koenigsegg-Ccxr-Trevita-580x326.jpg",
    image3 : "http://4.bp.blogspot.com/-MLBvvRLHrKc/VdttquO01mI/AAAAAAAAhgA/dOEox1gMczw/s1600/Floyd-Mayweather-Koenigsegg-CCXR-Trevita01.jpg",
    image4 : "http://fastdrive.me/wp-content/uploads/thon/koenigsegg-ccxr-trevita-hd-wallpaper-photos-pics-images-throughout-koenigsegg-ccxr-hd-wallpaper-1024x600.jpg",
    image5 : "http://freefuncar.com/wp-content/uploads/2017/03/KOENIGSEGG-ONE-1-SPORT-CARS-WALLPAPER.jpg",
    image6 : "https://www.koenigsegg.com/wp-content/uploads/2015/01/2010-Koenigsegg-Trevita-V2-1440.jpg",
    image7 : "https://wallpapercave.com/wp/wp1856763.jpg",
    image8 : "https://carswallpaper.in/wp-content/uploads/2016/03/koenigsegg_ccxr_interior-1920x1200.jpg",
    image9 : "http://luxurylaunches.com/wp-content/uploads/2015/08/koenigsegg-ccxr-trevita-2.jpg",
    description :  "<strong>The Koenigsegg CCXR Edition was created to break records in the traditional Koenigsegg way..</strong><p>At the time of its release, no other supercar the CCXR Edition in terms of power-to-weight ratio, aerodynamic balance, downforce and chassis stiffness. At the same time, the CCXR Edition maintained fantastic drivability with a chassis and suspension setup that could absorb uneven road surfaces like no other Hypercar.</p> ",
    description1 : "<h2>The Koenigsegg CCXR Edition featured a remapped, 4.8 litre twin-supercharged flexfuel:</h2><p>The CCXR Edition was only produced in four examples and featured a number of unique specifications including its 4.8 liter flexfuel engine, 11 spoke wheels, a unique rear wing, unique side winglets, etc. These features, in combination with the suberb fit and finish of the Koenigsegg all visible carbon body and chassis construction, truly made the CCXR Edition an unrivalled work of automotive art...</p>",

    type : "Koenigsegg aluminium V8, 4 valves per cylinder, double overhead ",
    displacement : " 4800 cc ",
    borexstroke : "Twin Rotrex centrifugal superchargers with response system, 1.6 bar boost pressure. ",
    compression : "9.2:1 ",
    maxpower : "1018 Bhp at 7000 rpm ",
    maxtorque : "1080 Nm (796 ft/lb) at 5600 rpm ",
    transmissiontype : "Torque sensitive limited slip differential. ",
    gearbox : "Specially developed transversal 6-speed gearbox, with optional paddle-shift. ",
    maxspeed :  " 400+ km/h (250+ mph) (without rear wing)",
    acceleration : " 0-100 km/h (0-62 mph) 2.9 seconds, 0-200 km/h 8.75 sec. 0-200-0 km/h 13.0 sec, 0-300-0 km/h: 25.5 Sec. ",
    rimf : "19″ x 9.5″ ",
    rimr : "20″ x 12.5″ ",
    tiref : "Front: 255/35 – 19″ (Y) ",
    tirer : "Rear: 335/30 – 20″ (Y) "
  },

  { name : "W-Motors-Lykan_",
    image : "http://www.hdwallpapers.in/download/w_motors_lykan_hypersport_2013-1920x1200.jpg",
    description :  "<strong>A modern machine with a touch of humanity.</strong><p>The Lykan Hypersport is a Lebanese limited production supercar built by W Motors, a United Arab Emirates based company, founded in 2012 in Lebanon with the collaboration of Lebanese, French and Italian engineers. It is the first supercar to be produced in the Middle East, and is featured in the film Furious 7, and the video games Project CARS, Driveclub, Asphalt 8: Airborne, Asphalt Nitro, Forza Motorsport 6, and GT Racing 2: The Real Car Experience, Forza Horizon 3, CSR Racing and CSR Racing 2. The Lykan can also be briefly seen in the second Fate of the Furious trailer, however, the Lykan does not make an appearance, the footage is from the seventh movie, Fast and Furious 7. It is the first car to be designed and produced indigenously in the Arab World.</p> ",
    description1 : "<h2>DESIGN A MASTERPIECE OF POWER AND LIGHTNESS INSPIRED BY AERONAUTICS:</h2><p>The manufacturer claims a top speed of 395 km/h (245 mph) and a time from 100 km/h (62 mph) in 2.8 seconds, however there have been no independent tests of the car's performance as of yet. There was a demonstration by W Motors in 2013 in Dubai, in which they claim to have recorded the car's performance. In June 2015, the Abu Dhabi police force purchased a Lykan HyperSport.[12] The Abu Dhabi Police car is included in the total of seven, meaning only six will be available for purchase..</p>",


    image1 : "https://images8.alphacoders.com/759/759718.jpg",
    image2 : "http://www.hdcarwallpapers.com/walls/2017_w_motors_lykan_hypersport-wide.jpg",
    image3 : "http://www.hdcarwallpapers.com/walls/2013_w_motors_lykan_hypersport_4-wide.jpg",
    image4 : "https://www.drivespark.com/img/2015/01/12-1421042346-lykan-hypersport-exterior.jpg",
    image5 : "http://wallpaperevo.com/wp-content/uploads/2014/03/W-Motors-Lykan-HyperSport-2014-4K-UHD-Wallpaper-730x353.jpg",
    image6 : "https://i.ytimg.com/vi/Y5SLAeNuFXk/maxresdefault.jpg",
    image7 : "http://www.car-revs-daily.com/wp-content/uploads/2013/12/CarRevsDaily-Supercars-Best-of-2013-W-Motors-Lykan-HyperSport-381.jpg",
    image8 : "https://images.hgmsites.net/lrg/w-motors-lykan-hypersport_100419058_l.jpg",
    image9 : "http://www.inautonews.com/wp-content/uploads/2013/02/lykan-supercar-w-motors-interior-3.jpg",

    type : "Boxer Type, 228.6 in3, 3746 cc Flat 6",
    displacement : "--",
    borexstroke : "Twin Turbocharger with Independent Intercooler",
    compression : "--",
    maxpower : "582KW (780hp) at 7100 rpm",
    maxtorque : "960Nm at 4000 rpm",
    transmissiontype : "Seven Speed Dual Clutch PDK",
    gearbox : "Transversely Rear Mounted",
    maxspeed :  "395 km/h (245 mph) (dependent on the gear ratios)",
    acceleration : "0-100 km/h (0-62 mph) in 2.8 sec",
    rimf : "8.5 x 19",
    rimr : "12.5 x 20",
    tiref : " 255/35 ZR 19",
    tirer : "335/30 ZR 20"
  },

  { name : "Bugatti_Veyron_",
    image : "https://www.hdwallpapers.in/walls/bugatti_veyron_9-wide.jpg",
    description :  "<strong>Bugatti Veyron Super Sport.</strong><p>Bugatti continued the brand tradition of developing Super Sport versions of successful models with the Veyron 16.4 Super Sport. The Veyron 16.4 Super Sport expanded the limits of possibility in the automotive sector even further and set new benchmarks..</p> ",
    description1 : "<h2>Perfect technology with a unique design :</h2><p>The guiding principle of the genius car designer Ettore Bugatti, who came from a family of artists, was to always encase perfect technology in an aesthetically appealing exterior. This commitment lives on today: the designers gave the Veyron 16.4 Super Sport an utterly unique appearance – and at the same time, every single exterior modification serves to improve performance. The Super Sport’s flat, elongated form is immediately recognisable. Instead of bonnet scoops, the 16-cylinder engine is ventilated by two NACA ducts in the roof..</p>",


    image1 : "https://images6.alphacoders.com/364/thumb-350-364732.jpg",
    image2 : "https://wallpapercave.com/wp/Z9zVoD6.jpg",
    image3 : "https://2hourbusiness.files.wordpress.com/2013/03/tumblr_mehev7crfq1rm3ahio1_500.jpg",
    image4 : "https://s-media-cache-ak0.pinimg.com/originals/3c/cb/bb/3ccbbbdd5d25d41be59bdba9c0801acb.jpg",
    image5 : "http://www.hotszots.eu/_galler/IMG/BUGATTI/Bugatti-Veyron-Grand-Sport-Roadster-Vitesse-hdwallpapers%20(9).jpg",
    image6 : "https://wallpapercave.com/wp/QpNM29z.jpg",
    image7 : "http://carjournals.net/wp-content/uploads/2015/12/car-wallpaper-hd-1920x1080-Bugatti-Veyron-164-Grand-Sport-Vitesse-Interior.jpg",
    image8 : "http://images.caricos.com/b/bugatti/2011_bugatti_veyron_super_sport/images/1920x1080/2011_bugatti_veyron_super_sport_78_1920x1080.jpg",
    image9 : "https://assets.bugatti.com/fileadmin/user_upload/Web/Pages/Models/Super_Sport/BUG_super_sport_13.jpg",

    type : "W 16",
    displacement : "7993 cm3",
    borexstroke : "84mm",
    compression : "8:3:1",
    maxpower : "882 kW ( 1 200 HP) at 6 400 rpm",
    maxtorque : "1 500 Nm at 3 000-5 000 rpm",
    transmissiontype : "",
    gearbox : "7-speed DSG",
    maxspeed :  "415 km/h ",
    acceleration : "0 – 100 km/h 	2.5 sec 0 - 100 km/h",
    rimf : "--",
    rimr : "--",
    tiref : "265-680 ZR500",
    tirer : "265-710 ZR540"
  },

  { name : "LaFerrari_",
    image : "http://s3.amazonaws.com/digitaltrends-uploads-prod/2017/04/FLF-DALSPR17465.png",
    description :  "<strong>Ferrari’s  most ambitious project.</strong><p>It boasts the most extreme performance ever achieved by a Ferrari production car and features the most advanced and innovative technical solutions which will, in the future, filter down to the rest of the Ferrari range..</p> ",
    description1 : "<h2>Engineering and design in synergy:</h2><p>LaFerrari was designed by the Ferrari Styling Centre which worked in synergy with the engineering and development departments from the very start of the model’s inception..</p>",


    image1 : "http://auto.ferrari.com/en_EN/wp-content/uploads/sites/5/2013/10/Ferrari-LaFerrari-three-quarter-1260x570.jpg",
    image2 : "https://cdn.jamesedition.com/media/W1siZiIsImxpc3RpbmdfaW1hZ2VzLzIwMTcvMDgvMTIvMDUvMTIvMzIvOGMyMGExNjktNTQ1NS00NjFkLWIyZDItZjlkYzllNmI3YTNkLzIxMDJfMDY5NDVhNDc0MV9sb3dfcmVzLmpwZyJdLFsicCIsInRodW1iIiwiMjAwMHgiXSxbInAiLCJ3YXRlcm1hcmsiXSxbInAiLCJlbmNvZGUiLCJqcGciLCItc3RyaXAgLXF1YWxpdHkgODAgLWludGVybGFjZSBQbGFuZSJdXQ/2014-ferrari-laferrari.jpg?sha=7a3b32c29133e67a",
    image3 : "https://blog.caranddriver.com/wp-content/uploads/2013/03/2014-Ferrari-LaFerrari-202-626x382.jpg",
    image4 : "https://2p2bboli8d61fqhjiqzb8p1a-wpengine.netdna-ssl.com/wp-content/uploads/2017/07/bianco-fuji-laferrari-7252017-7-520x338.jpg",
    image5 : "https://img.newatlas.com/new-laferrari-aperta-could-break-auction-records-4.jpg?auto=format%2Ccompress&fit=max&h=670&q=60&w=1000&s=140bcebdc657eb31140370c048d6b079",
    image6 : "https://mrcollection.com/wp-content/uploads/2016/11/la_ferrari_aperta_nero_daytona-2.jpg",
    image7 : "https://cnet2.cbsistatic.com/img/2PEPGhQYbBnfYh_dwZYea30X7t4=/770x433/2016/09/29/fa66b3d7-5179-42e3-bc55-56d2f2625d97/2018-ferrari-laferrari-aptera-7-of-14.jpg",
    image8 : "https://cdn.jamesedition.com/media/W1siZiIsImxpc3RpbmdfaW1hZ2VzLzIwMTcvMTIvMjIvMTYvMDQvNTQvYWJkYTEyMDAtMGQxZS00NWJkLWIwMDMtMDUyMzIxNGM0Njc2LzEuanBnIl1d/2015-ferrari-laferrari-1-of-120-for-the-u-s-market-317-miles.jpg?sha=7dfd07b7b942383e",
    image9 : "http://www.telegraph.co.uk/cars/images/2015/12/11/LaFerrari-dashboard_trans_NvBQzQNjv4BqjJeHvIwLm2xPr27m7LF8md8oAmGZYX8Vqbq2hlobTFc.jpg?imwidth=480",

    type : "The 6262cc V12 produces 800 CV and the electric motor a further 12o kW (163 CV) for a total of over 960 CV.",
    displacement : "6262 cc",
    borexstroke : "94 x 75,2 mm",
    compression : "13.5:1",
    maxpower : "800 CV @9000 rpm",
    maxtorque : "700 Nm @6750 rpm",
    transmissiontype : "--",
    gearbox : "7-speed DCT",
    maxspeed :  "350 km/h ",
    acceleration : "0-100 KM/H (0-62 MPH)3 sec",
    rimf : "--",
    rimr : "--",
    tiref : "265/30 - 19",
    tirer : "345/30 - 20"
  },

  { name : "Pagani_Huayra_",
    image : "https://wallpapercave.com/wp/qT9AzrC.jpg",
    description :  "<strong>Huayra .</strong><p>After seven years of hard work I am now able to tell you a little brief history and the path that led to the birth of the Huayra, project name C9.The concept was born in 2003, the year of the introduction of the Zonda S Roadster. As you may recall the early 2000s were prosperous for the world of supercars. The commitment of big car manufacturers have contributed to the rise of extraordinary cars like the Bugatti Veyron, Porsche Carrera GT, Ferrari Enzo, Mercedes McLaren SLR..</p> ",
    description1 : "<h2>This context led us to make several observations concerning the future of the Zonda and what could be a new Pagani. :</h2><p>Since the original design of the Zonda was done in the early 90s the first thought was that it was now an obsolete project and we decided to imagine the car totally different in form, dimension, dynamics and technology, all this without losing the essence of our approach, to follow a concept born in the Renaissance where Leonardo da Vinci told us that art and science are disciplines that need to walk alongside. The eternal element air in all its forms, especially wind, became determining in defining the concept and it was a great inspiration, as it is ever present in our lives: a jet turbine, the silence of a glider… the elegance of the wind movements but also the violence and force that it can unleash..</p>",


    image1 : "http://images.caricos.com/p/pagani/2012_pagani_huayra/images/1920x1080/2012_pagani_huayra_4_1920x1080.jpg",
    image2 : "https://images7.alphacoders.com/350/thumb-1920-350542.jpg",
    image3 : "https://wallpaperscraft.com/image/pagani_huayra_side_view_108112_1366x768.jpg",
    image4 : "https://pbs.twimg.com/media/DRChunCXUAAMP6X.jpg",
    image5 : "http://img.gawkerassets.com/img/18snrojhm905bjpg/original.jpg",
    image6 : "http://www.hdcarwallpapers.com/thumbs/pagani_huayra_gran_turismo_6-t2.jpg",
    image7 : "http://wallsdesk.com/wp-content/uploads/2016/03/Pagani-Huayra-BC-full-HD.jpg",
    image8 : "http://hdlatestwallpaper.com/wp-content/uploads/2017/05/Pagani-Huayra-interior-HD-wallpaper.jpg",
    image9 : "http://hd.wallpaperswide.com/thumbs/pagani_huayra_drivers_side_interior-t2.jpg",

    type : "Mercedes-AMG M158",
    displacement : "5980CC",
    borexstroke : "95 mm x 76,4 mm (3.74 x 3.01 in)",
    compression : "11,8:1",
    maxpower : " (536 kW) @ 8.400 rpm",
    maxtorque : "1.00 Nm  FROM 2.600rpm TO 4.200 rpm",
    transmissiontype : "Electronically controlled all-wheel drive system (Haldex gen. IV) with rear mechanical self-locking differential",
    gearbox : "transversal SEQUENTIAL 7 speeds",
    maxspeed :  "355 km/h (221 mph)",
    acceleration : "0-100 KM/H (0-62 MPH)2,9S",
    rimf : "FRONT20'' specific forged rims; 9J x 20 ET32.2",
    rimr : "REAR21'' specific forged rims; 13J x 21 ET66.7",
    tiref : "FRONT255/30 ZR20",
    tirer : "REAR355/25 ZR21"
  },

  { name : "Ferrar_f60_America_",
    image : "http://www.hdcarwallpapers.com/walls/2015_ferrari_f60america-wide.jpg",
    description :  "<strong>The hand-over at the Palm Beach Cavallino Classic.</strong><p>Palm Beach, 25th January – The first F60 America was delivered this weekend to the delight of a discerning crowd of Ferrari collectors and enthusiasts during the 25th annual Palm Beach Cavallino Classic..</p> ",
    description1 : "<h2>This beautiful example in Blu Nart livery :</h2><p>This strictly limited-edition car, which was produced to commemorate the 60th Anniversary of Ferrari in America, is the first of just ten to be delivered nationwide. The car pays homage to American clients’ great passion for both the V12 engine and open-top driving. The F60 America’s bodywork adopts the classic North American Racing Team livery, and the special Ferrari 60th Anniversary Prancing Horse badge on the wheelarches appears on the tunnel in the cockpit.</p>",


    image1 : "https://i.ytimg.com/vi/-R6gQyrOuKI/maxresdefault.jpg",
    image2 : "https://images3.alphacoders.com/631/thumb-350-631129.jpg",
    image3 : "https://pictures.dealer.com/f/ferrariofsanfrancisco/1500/d0034736750867cac0aaa8644d2dc334x.jpg",
    image4 : "http://hdwallpaperbackgrounds.net/wp-content/uploads/2015/08/2015-Ferrari-F60-America-Rear-Side-Wallpapers-Desktop-HD.jpg",
    image5 : "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/ferrari-f60-america-002.jpg?itok=0O5gGzra",
    image6 : "https://carimages.com.au/ENYKZAp2hLk8R6QgnMRUFh_GXKo=/fit-in/930x620/filters:stretch(FFFFFF)/editorial/articleLeadwide-the-interior-features-is-designed-around-the-drive115aoa.jpg",
    image7 : "https://madwhips.s3.amazonaws.com/photo_9213_ferrari_f60_america_316920_wt.jpg",
    image8 : "http://www.looksmartmodels.com/wp-content/uploads/2016/09/Ferrari-F60-America-05.jpg",
    image9 : "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/_P__6162_1.jpg?itok=gnNHtVTE",

    type : "mid-front-mounted V12",
    displacement : "6.498 cm³ (396.5 cu in)",
    borexstroke : "95 mm x 76,4 mm (3.74 x 3.01 in)",
    compression : "11,8:1",
    maxpower : "750 CV (552 kW) @ 8.400 rpm",
    maxtorque : "690 Nm (507 lb.-ft.) @ 5.500 rpm",
    transmissiontype : "Electronically controlled all-wheel drive system (Haldex gen. IV) with rear mechanical self-locking differential",
    gearbox : "7 gear dual clutch",
    maxspeed :  "355 km/h (221 mph)",
    acceleration : "0-100 KM/H (0-62 MPH)2,9S",
    rimf : "FRONT20'' specific forged rims; 9J x 20 ET32.2",
    rimr : "REAR21'' specific forged rims; 13J x 21 ET66.7",
    tiref : "FRONT255/30 ZR20",
    tirer : "REAR355/25 ZR21"
  },

  { name : "Bugatti_Chiron_",
    image : "https://assets.bugatti.com/fileadmin/user_upload/Web/Pages/Chiron_2017/Bugatti-chiron-carbon-blue.jpg",
    description :  "<strong>LAMBORGHINI VENENO: IT WILL FEEL LIKE FLYING ON THE ROAD.</strong><p>The Lamborghini Veneno Roadster takes the aerodynamic efficiency of a racing prototype onto everyday roads. This super sports car is characterized by optimal aerodynamics in order to guarantee stability in fast curves and a behavior like a racing prototype. All of this on a car devised for the road. The perfect car for sports-driving lovers.</p> ",
    description1 : "<h2>DESIGN A MASTERPIECE OF POWER AND LIGHTNESS INSPIRED BY AERONAUTICS:</h2><p>Here are the technical specifications of the new Veneno: with a 6.5 liter aspirated V12 engine and a top speed of 355 km/h, this Lamborghini concept car represents state-of-the-art design inspired by aeronautics, capable of giving you the indescribable feeling of flying on the road. Faithful to the Lamborghini lines, the Veneno is characterized by extreme proportions, emerging in the forceful arrow-shaped front as well as alternating razor-sharp lines and sleek, tight surfaces.</p>",


    image1 : "https://i.ytimg.com/vi/PkkV1vLHUvQ/maxresdefault.jpg",
    image2 : "https://storage.googleapis.com/gtspirit/uploads/2017/03/Bugatti-Chiron12.jpg",
    image3 : "https://s.aolcdn.com/dims-global/dims3/GLOB/legacy_thumbnail/916x515/quality/95/https://s.blogcdn.com/slideshows/images/slides/493/384/4/S4933844/slug/l/01-bugatti-chiron-fd-1.jpg",
    image4 : "https://assets.bugatti.com/typo3conf/ext/bugatti_specials/Resources/Public/Template/content/chiron/backside/backside.jpg",
    image5 : "https://www.driving.co.uk/s3/st-driving-prod/uploads/2017/07/chiron-02.jpg",
    image6 : "https://cdn.gearpatrol.com/wp-content/uploads/2017/09/Bugatti-Chiron-gear-patrol-6-1940x1300.jpg",
    image7 : "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/bugatti-chiron-centre-console.jpg?itok=Qrwn6SMv",
    image8 : "https://www.netcarshow.com/Bugatti-Chiron-2017-1600-5f.jpg",
    image9 : "http://images.caricos.com/b/bugatti/2017_bugatti_chiron/images/2560x1440/2017_bugatti_chiron_53_2560x1440.jpg",

    type : "W 16",
    displacement : "7993 cm3",
    borexstroke : "84mm",
    compression : "8:3:1",
    maxpower : "882 kW ( 1 200 HP) at 6 400 rpm",
    maxtorque : "1 500 Nm at 3 000-5 000 rpm",
    transmissiontype : "",
    gearbox : "7-speed DSG",
    maxspeed :  "415 km/h ",
    acceleration : "0 – 100 km/h 	2.5 sec 0 - 100 km/h",
    rimf : "--",
    rimr : "--",
    tiref : "265-680 ZR500",
    tirer : "265-710 ZR540"
  },

  { name : "Lamborghini_Sesto_elemento",
    image : "https://img.gta5-mods.com/q95/images/lamborghini-sesto-elemento/37c007-24275443603_63d47c8df5_h.jpg",
    description :  "<strong>DRIVABILITY Amazing power-to-weight ratio..</strong><p>Automobili Lamborghini is redefining the future of super sports cars with this very limited special edition.Boasting an extremely lightweight construction thanks to advanced carbon fiber technology, the Lamborghini Sesto Elemento has an overall curb weight of just 999 kilograms (2,202 lb) - including the V10 power unit and the permanent all-wheel drive. With its sensational power-to-weight ratio of only 1.75 kilograms per CV, this limited-edition super sports car offers unrivalled performance: from 0 to 100 km/h in a record time of only 2.5 seconds..</p> ",
    description1 : "<h2>DESIGN Sensuous and innovative.:</h2><p>Exhibiting uncompromising dynamics from the very first glance, the design of the Lamborghini Sesto Elemento displays the sensuality of high performance and possesses the elegance of pure, unadulterated power.The Sesto Elemento elevates the style DNA of the Lamborghini brand to a new level, and integrates the functional consistency of carbon fiber technology into its design language..</p>",


    image1 : "https://icdn3.digitaltrends.com/image/_dsc1563-640x427-c.jpg?ver=1",
    image2 : "https://images6.alphacoders.com/343/thumb-1920-343136.jpg",
    image3 : "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Lamborghini_Sesto_Elemento_%2816107850781%29.jpg/1200px-Lamborghini_Sesto_Elemento_%2816107850781%29.jpg",
    image4 : "https://www.hiroboy.com/thumbnail/1200x1200/userfiles/images/sys/products/124_Lamborghini_Sesto_Elemento_Oversea_Edition_38814.jpeg",
    image5 : "https://icdn-6.motor1.com/images/mgl/wjk2o/s4/lamborghini-sesto-elemento1.jpg",
    image6 : "http://www.lambocars.com/images/lambonews/sesto_elemento_hong_kong_5.jpg",
    image7 : "https://www.ihdimages.com/wp-content/uploadsktz/2014/10/lamborghini_sesto_elemento_interior_wallpaper_widescreen.jpg",
    image8 : "http://2.bp.blogspot.com/-AnXGnBFOr7Q/VAQtDEGu3EI/AAAAAAAACSM/kvxRViVgWZQ/s1600/sesto02.jpg",
    image9 : "http://shows.autospies.com/gallery/auto-show-photos.asp?imageId=107056&galleryId=209",

    type : "Odd-firing 5.2 L FSI V10 570HP",
    displacement : "6.498 cm³ (396.5 cu in)",
    borexstroke : "95 mm x 76,4 mm (3.74 x 3.01 in)",
    compression : "11,8:1",
    maxpower : "750 CV (552 kW) @ 8.400 rpm",
    maxtorque : "690 Nm (507 lb.-ft.) @ 5.500 rpm",
    transmissiontype : "Electronically controlled all-wheel drive system (Haldex gen. IV) with rear mechanical self-locking differential",
    gearbox : "6-speed semi-automatic transmission with paddle shift",
    maxspeed :  " (210 mph)",
    acceleration : "0-100 KM/H (0-62 MPH)2.5S",
    rimf : "FRONT20'' specific forged rims; 9J x 20 ET32.2",
    rimr : "REAR21'' specific forged rims; 13J x 21 ET66.7",
    tiref : "FRONT255/30 ZR20",
    tirer : "REAR355/25 ZR21"
  },

  {
    name: "Aston_Martin_One-77_",
    image: "http://cdntbs.astonmartin.com/sitefinity/beauty/rga_astonmartin_cars_beauty_one-77_02.jpg?sfvrsn=0",
    description: "<h2>One-77</h2><p>The One-77, a sports car of unparalleled beauty with subtle aggression and performance developed in 2008 and 2009 with the goal of eclipsing any previous Aston Martin road car.</p>",
    description1:"<h2>The Ultimate Aston Martin</h2><p>Tantalisingly, the first glimpse the world got of the One-77 hypercar was a maquette of the new car at the 2008 Paris Motor Show, three quarters covered by a grey pin-stripe fabric cover with only a glimpse of the front right side coyly peeping out.</p>",
    image1: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Aston_Martin_One-77_-_Flickr_-_skinnylawyer.jpg/1200px-Aston_Martin_One-77_-_Flickr_-_skinnylawyer.jpg",
    image2: "https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/images/media/267456/2010-aston-martin-one-77-photo-263747-s-original.jpg",
    image3: "https://3.bp.blogspot.com/-jgOazhhndoE/WVA5Ylm5e0I/AAAAAAAAuwI/Qm-4B1n6Em89IegUb09-vPAzyWfZJJiJgCLcBGAs/s1600/Aston-Martin-One-77-Q-Series-5.jpg",
    image4: "http://blog.caranddriver.com/wp-content/uploads/2009/12/m4y5v36g.jpg",
    image5: "https://img.pistonheads.com/LargeSize/aston-martin/one-77/aston-martin-one-77-S2709983-1.jpg",
    image6: "https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/images/08q4/267455/aston-martin-one-77-photo-233956-s-original.jpg",
    image7: "http://cdntbs.astonmartin.com/sitefinity/beauty/rga_astonmartin_cars_beauty_one-77_05.jpg?sfvrsn=0",
    image8: "https://img.gta5-mods.com/q95/images/aston-martin-one-77-autovista-auto-spoiler-add-on/816bd2-One-77%20Interior.jpg",
    image9: "http://www.thesupercarblog.com/wp-content/uploads/2017/02/Striking-Blue-Aston-Martin-One-77-For-Sale-in-the-US-6.jpg",
    type : "Alloy quad overhead camshaft, 48-valve, 7312 cc V12",
    displacement : "7312cc",
    borexstroke : "--",
    compression : "10.9:1",
    maxpower : "559 kW (750 bhp/760 PS)",
    maxtorque : "750 Nm",
    transmissiontype : "Rear mid-mounted, six-speed automated manual gearbox with auto shift ",
    gearbox :"Limited-slip differential",
    maxspeed :  "354 km/h (220 mph)",
    acceleration :"354 km/h (220 mph)",
    rimf :"20 forged alloy wheels – 7 or 10-spoke – bespoke finishes",
    rimr : "20 forged alloy wheels – 7 or 10-spoke – bespoke finishes",
    tiref : "P Zero Corsa 255/35 ZR20",
    tirer :"P Zero Corsa 335/30 ZR20",
  },

  {
    name: "Zenvo-St1_",
    image: "http://hdpixl.com/wp-content/uploads/2017/03/Zenvo-St1-HD-Wallpaper-For-Desktop-1024x640.jpg",
    description: "<p>ST1 V8 is a supercar manufactured by the Danish hyper car maker company Zenvo. ST1 is the first car from the company </p>",
    description1:"<p>Zenvo ST1 V8 is powered by a 7000cc V8 engine which generates a maximum power of 1104 bhp @ 6900 rpm and at a maximum torque of 1430 Nm @ 4500 rpm. The car runs on a 6 speed manual transmission with petrol engine. The supercar makes it from 0 to 100 kmph in just 3 seconds with a top speed of 375 kmph. It has a 2 seater passenger capacity with a boot space of 130 litres. It is a competitor to Ferrari LaFerrari and Lamborghini </p>",
    image1: "http://wallsdesk.com/wp-content/uploads/2016/10/Zenvo-St1-HD-Wallpaper.jpg",
    image2: "http://www.wallpapers-web.com/data/out/217/5734050-zenvo-st1-wallpapers.png",
    image3: "https://www.netcarshow.com/Zenvo-ST1-2010-1600-07.jpg",
    image4: "http://www.seriouswheels.com/pics-2009/r-z-0-9/2009-Zenvo-ST1-Studio-Rear-Angle-Low-View-1600x1200.jpg",
    image5: "https://pre00.deviantart.net/7242/th/pre/f/2010/230/b/5/zenvo_zt1_goldfish_by_jackdarton.jpg",
    image6: "https://s-media-cache-ak0.pinimg.com/originals/56/cf/43/56cf43206b0f6946323c110181bf825f.jpg",
    image7: "http://www.hdcarwallpapers.com/walls/zenvo_devon_st1_interior-wide.jpg",
    image8: "https://i.ytimg.com/vi/kxhrvHGi1wo/maxresdefault.jpg",
    image9: "https://gearheads.org/wp-content/uploads/2015/06/zenvo5.jpg",
    type : " 	7400cc, V8",
    displacement : "7400cc",
    borexstroke : "--",
    compression : "--",
    maxpower : "1104 Bhp @ 6900 rpm",
    maxtorque : " 	1430 Nm @ 4500 rpm",
    transmissiontype : "7-speed paddle shift; 6-speed manual",
    gearbox :"7-speed paddle shift; 6-speed manual",
    maxspeed :  "375 km/hr",
    acceleration :"0-100 kmph -3.00 seconds",
    rimf :"--",
    rimr : "--",
    tiref : "255/35–19",
    tirer :"335/30–20",
  },


  {
    name: "McLaren_P1_",
    image: "https://www.hdwallpapers.in/walls/2016_mclaren_p1_mso-HD.jpg",
    description: "<h2>Designed, engineered and built to be the best driver’s car in the world.</h2><p>The McLaren P1™ follows in the footsteps of the iconic McLaren F1, the car that pushed boundaries further than any of its rivals.</p>",
    description1:"<h2>Design and Innovation</h2><p>What would nature do? The purposeful appearance of the McLaren P1™ is the result of a function-led design approach.</p>",
    image1: "https://wallpapercave.com/wp/wp1822335.jpg",
    image2: "http://www.hdcarwallpapers.com/walls/mclaren_p1-wide.jpg",
    image3: "https://www.hdwallpapers.in/walls/mclaren_p1-HD.jpg",
    image4: "https://images7.alphacoders.com/494/494661.jpg",
    image5: "https://wallpapersite.com/images/wallpapers/mclaren-p1-1920x1080-racing-forza-motorsport-5-5k-10074.jpg",
    image6: "https://images7.alphacoders.com/460/460370.jpg",
    image7: "http://images.caricos.com/m/mclaren/2014_mclaren_p1/images/1920x1080/2014_mclaren_p1_23_1920x1080.jpg",
    image8: "http://monthlymale.com/wp-content/uploads/2016/03/mclaren-p1-interior.jpg",
    image9: "http://images.caricos.com/m/mclaren/2015_mclaren_p1_prost/images/1920x1080/2015_mclaren_p1_prost_8_1920x1080.jpg",
    type : "win-turbocharged and intercooled DOHC 32-valve 3.8-liter V-8, 727 hp, 531 lb-ft;",
    displacement : "3799cc.",
    borexstroke : "93 mm-69 mm",
    compression : "--",
    maxpower : " 	1000 PS",
    maxtorque : " 	531 lb·ft @ 4,000 rpm (720 N·m)",
    transmissiontype : "7-speed dual-clutch automatic with manual shifting mode",
    gearbox :"7-speed dual-clutch automatic with manual shifting mode",
    maxspeed :  "217 mph",
    acceleration :"2.8 s (manufacturer)",
    rimf :"--",
    rimr : "--",
    tiref : "P245/35ZR19",
    tirer :" 	P245/35ZR19",
  },

  {
    name: "Ferrari-Pininfarino_",
    image: "https://s-media-cache-ak0.pinimg.com/originals/d2/58/3f/d2583f2555755ad8a116a7877e285354.jpg",
    description: "<p>If there was ever a concept that truly embodied the long-standing partnership between Ferrari and Pininfarina, it would be the 2013 Ferrari Sergio. The concept burst onto the scene at the 2013 Geneva Motor Show as a tribute model to the late Sergio Pininfarina. Reports that the Sergio was earmarked for production first surfaced in September 2014, and a little over a month later, a new report indicated that Ferrari and Pininfarina were actually building production models of the radical concept. Now, the wait is over, as it was recently officially announced that the first Ferrari Sergio has been delivered to the SBH Royal Auto Gallery at Abu Dhabi’s Yas Marina Circuit in the United Arab Emirates.<p>",
    description1:"<p>Ferrari and Pininfarina, the two architects behind the Sergio Concept, built six production versions of the radical supercar, each coming with a price tag of $3 million. The price is admittedly way more than I can afford, but for the six individuals Ferrari invited to snatch up the limited-edition piece, spending $3 million on an ultra-exclusive supercar can be considered money well spent.</p>",
    image1: "http://images.caricos.com/p/pininfarina/2013_pininfarina_ferrari_sergio/images/1920x1080/2013_pininfarina_ferrari_sergio_48_1920x1080.jpg",
    image2: "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/pinifarina-sergio-concept-1-006.jpg?itok=P_xGeQ5z",
    image3: "https://ag-log.o.auroraobjects.eu/07-2014/sergio_concept/2.jpg?last_change=1406024161",
    image4: "https://icdn-3.motor1.com/images/mgl/bmVor/s1/2014-499009-pininfarina-sergio-production-version-not-confirmed1.jpg",
    image5: "http://cardesignnews.com/media/imported/servlet/file/274654_68.jpg",
    image6: "http://news.hrowen.co.uk/wp-content/uploads/2014/08/Ferrari-Pininfarina-Sergio-4.png",
    image7: "http://images.caricos.com/p/pininfarina/2013_pininfarina_ferrari_sergio/images/1280x960/2013_pininfarina_ferrari_sergio_57_1280x960.jpg",
    image8: "https://www.designboom.com/wp-content/uploads/2014/12/ferrari-sergio-production-designboom04.jpg",
    image9: "http://images.caricos.com/p/pininfarina/2013_pininfarina_ferrari_sergio/images/1920x1080/2013_pininfarina_ferrari_sergio_4_1920x1080.jpg",
    type : "4.5 L Ferrari F136 F V8",
    displacement : "4499 cc",
    borexstroke : "--",
    compression : "--",
    maxpower : "570 bhp /  419 kW",
    maxtorque : "540 Nm @ 6000 rpm",
    transmissiontype : "7-speed dual-clutch",
    gearbox :"7-speed dual-clutch",
    maxspeed :  " 320 kph /  199 mph",
    acceleration :"(100 km/h) in 3.4 seconds.",
    rimf :"--",
    rimr : "--",
    tiref : "--",
    tirer :"--",
  },


  {
    name: "Aston_martin_Valkyrie_",
    image: "http://www.hdcarwallpapers.com/walls/aston_martin_valkyrie_v12_hypercar_2017-HD.jpg",
    description: "<h2>Power of the gods</h2><p>An incredibly special car with an equally remarkable name. One that immediately evokes connotations of power and honor, of being chosen by the Gods.Only 150 road cars will be made. Valkyrie is Aston Martin’s first ever hypercar and it leaves nothing in reserve.</p>",
    description1:"<h2>Radical aerodynamics</h2><p>A striking aerodynamic exterior and an open underfloor maximizes downforce and harnesses the atmosphere around Valkyrie. The all-carbon fiber bodywork carries our trademark upper grille outline, before forming into a radical body utterly honed for performance.</p>",
    image1: "http://images.caricos.com/a/aston_martin/2018_aston_martin_valkyrie/images/2560x1440/2018_aston_martin_valkyrie_1_2560x1440.jpg",
    image2: "https://icdn-1.motor1.com/images/mgl/pkbJW/s1/aston-martin-am-rb-001-hybrid-in-toronto.jpg",
    image3: "https://img00.deviantart.net/6eac/i/2017/066/b/7/aston_martin_valkyrie_by_jackdarton-dart021.png",
    image4: "https://icdn-4.motor1.com/images/mgl/ve9Y4/s1/aston-martin-am-rb-001.jpg",
    image5: "http://luxurylaunches.com/wp-content/uploads/2017/03/aston-martin-valkyrie-5-770x433.jpg",
    image6: "http://images.caricos.com/a/aston_martin/2018_aston_martin_valkyrie/images/1280x960/2018_aston_martin_valkyrie_10_1280x960.jpg",
    image7: "http://cdntbs.astonmartin.com/sitefinity/news/aston-martin-valkyrie_10-news.jpg?sfvrsn=0",
    image8: "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/images/car-reviews/first-drives/legacy/aston-899.jpg?itok=qrPSyXfZ",
    image9: "https://i.ytimg.com/vi/vD7gWmOH2DI/maxresdefault.jpg",
    type : "6.5-litre V12 engine developed with Cosworth",
    displacement : " 	6,500 cc / 396.7 cu in",
    borexstroke : "--",
    compression : "--",
    maxpower : " 	1,130 hp (843 kW; 1,146 PS",
    maxtorque : "--",
    transmissiontype : "7-speed Ricardo dual-clutch",
    gearbox :"Ricardo 7 speed Automatic ",
    maxspeed :  "250 mph (402 km/h)",
    acceleration :"--",
    rimf :"20in front",
    rimr : "21in rear",
    tiref : " 265/35-ZR20",
    tirer :"325/30-ZR21",
  },


  {
    name: "Koenigsegg_Agera-R_",
    image: "http://www.hdcarwallpapers.com/walls/2016_koenigsegg_agera_final_one_of_one_4-wide.jpg",
    description: "<h2>Thor’s hammer </h2><p>The Koenigsegg Agera R was produced between 2011 and 2014. 18 examples of the Agera R were produced during that time.The Agera R built upon the features and functionality of the Agera with new, unique solutions to enhance both performance and visual appearance even further.Enhancements included: visible carbon on the front bonnet and bumper, new front side winglets, an all-new Aero exhaust, increased engine power with a raised RPM limit.Koenigsegg was the first Hypercar manufacturer to take steps toward green technology with the release of the biofuel CCXR in 2007. The Agera R, based on the critically acclaimed Agera, follows in the footsteps of the CCXR as it also runs on biofuel.</p>",
    description1:"<h2>Agera R maximum flexibility </h2><p>In order to give the Agera R maximum flexibility when it comes to power delivery, Koenigsegg has implemented the latest technology when it comes to turbo materials and design. This reduces the inertia of the turbine wheel and axle and therefore gives improved response.</p>",
    image1: "http://7wallpapers.net/wp-content/uploads/11_Koenigsegg-Agera-R.jpg",
    image2: "http://www.hdcarwallpapers.com/walls/2015_koenigsegg_agera_hh-HD.jpg",
    image3: "https://wallpaperscraft.com/image/koenigsegg_agera_r_auto_2013_83876_3840x2400.jpg",
    image4: "http://vidzspot.com/wp-content/uploads/2017/09/h2cV8J.jpg",
    image5: "http://wallpapers-best.com/uploads/posts/2015-10/1_koenigsegg_agera_r.jpg",
    image6: "http://images.caricos.com/k/koenigsegg/2013_koenigsegg_agera_r/images/1920x1080/2013_koenigsegg_agera_r_10_1920x1080.jpg",
    image7: "https://s-media-cache-ak0.pinimg.com/originals/b1/35/57/b135576aa855a752945f87590f26b74d.jpg",
    image8: "http://images.caricos.com/k/koenigsegg/2013_koenigsegg_agera_r/images/1920x1080/2013_koenigsegg_agera_r_16_1920x1080.jpg",
    image9: "https://s-media-cache-ak0.pinimg.com/originals/a9/bf/41/a9bf417cd7e3d517b2c9ad93fd3fe0d6.jpg",
    type : "Koenigsegg aluminum 5.0L V8, 4 valves per cylinder, DOHC, titanium connecting rods, dry sump lubrication, with negative crank pressure functionality. ",
    displacement : "5000cc",
    borexstroke : "91.7 mm - 95.25 mm ",
    compression : "9.0:1 ",
    maxpower : "1140 hp at 7100 rpm – redline @ 7500 rpm ",
    maxtorque : "1200 Nm at 4100 rpm ",
    transmissiontype : "Specially developed 7-speed dual clutch, 1 input shaft transmission with paddle-shift. ",
    gearbox :"Electronic differential ",
    maxspeed :  "420+ km/h ",
    acceleration :" 0-100 km/h (0-62 mph) 2.8 sec.",
    rimf :"19″ x 9.5″ ",
    rimr : " 20″ x 12.5″ ",
    tiref : "265/35 – 19″ (Y) ",
    tirer :" 345/30 – 20″ (Y) ",
  },


  {
    name: "Hennessey_Venom_",
    image: "https://wallpaperdownload.xyz/wp-content/uploads/2016/10/hennessey-venom-gt-wallpaper-HD1.jpg",
    description: "<h2>Las Vegas, NV and Sealy, TX </h2><p>November 1, 2017. Today at the Shell “Pioneering Performance” experience at the 2017 SEMA Show in Las Vegas, NV, John Hennessey of Hennessey Special Vehicles will unveil the much-anticipated Venom F5. Together, Shell, Pennzoil and Hennessey have broken barriers, set records and now they’ve co-engineered the next big thing in the automotive industry - and that’s still just the beginning.</p>",
    description1:"<p>The Venom F5 is an all-new hypercar designed and built from the ground up with one goal in mind: To be the absolute fastest road car on earth. Hennessey and team have developed a completely new design, chassis and carbon fiber body focused on aerodynamics to achieve the lowest possible drag. The new F5 design features active aero that will yield a coefficient of drag of just 0.33.</p>",
    image1: "http://www.hdwallpaperup.com/wp-content/uploads/2014/12/hennessey-venom-gt.jpg",
    image2: "https://www.carpixel.net/w/51fc1dd71e87d272aad6bac8e0e3ebca/hennessey-venom-gt-spyder-wallpaper-hd-11668.jpg",
    image3: "http://xdesktopwallpapers.com/wp-content/uploads/2012/04/2011%20Hennessey%20Venom%20GT%20Side%20Pose%20In%20Silver.jpg",
    image4: "http://allfreewallpaper.com/wp-content/uploads/2017/07/hennessey-venom-gt-hd-wallpaper.jpg",
    image5: "http://timothykurek.com/wp-content/uploads/2017/10/hennessey-venom-gt-hd-wallpapers-interior-images-and-photos-on-hennessey-venom-gt-hd-wallpaper.jpg",
    image6: "https://cdn.barrett-jackson.com/staging/carlist/items/Fullsize/Cars/198096/198096_Interior_Web.jpg",
    image7: "http://www.seriouswheels.com/pics-ghi/Hennessey-Venom-GT-Dark-Knight-Interior-Details-9-1680x1050.jpg",
    image8: "http://celebritiesgallery.in/wp-content/uploads/2016/08/Hennessey-Venom-GT-New-Wallpaper-580x387.jpg",
    image9: "http://cs2.gamemodding.net/images/5407a6f656e3b5b14b7e0911eb2e44a435bd60c7696344ceef47d89255fa3a80.jpg",
    type : "1600 bhp Hennessey Twin Turbo V8 Engine",
    displacement : "7000 cc",
    borexstroke : "--",
    compression : "9.2:1",
    maxpower : "1,600 bhp (1,193 kW; 1,622 PS)",
    maxtorque : "1,300 lb⋅ft (1,763 N⋅m)",
    transmissiontype : "7-speed single clutch paddle shift transmission",
    gearbox :"6-Speed Manual",
    maxspeed :  "301 mph (484 km/h)",
    acceleration :"0-100 kmph-2.7 seconds",
    rimf :"Hennessey H10 forged monoblock",
    rimr : "Hennessey H10 forged monoblock",
    tiref : " 	265/30ZR19",
    tirer :"345/30ZR20",
  },

  {
    name: "9ff-GT-9 r_",
    image: "http://www.clutchd.com/wp-content/gallery/05_april_2010-9ff-gt9-r-crashes-at-vmax-armageddon/clutchd-com-9ff-gt9-r-crashes-at-vmax-armageddon-4.jpg",
    description: "<h2></h2><p></p>",
    description1:"<h2></h2><p></p>",
    image1: "http://www.ultimatecarpage.com/images/car/3923/9ff-GT9-R-31365.jpg",
    image2: "https://s-media-cache-ak0.pinimg.com/originals/3e/d5/1e/3ed51e97ebb3e9ed28319f08e77e0b97.jpg",
    image3: "https://i.ytimg.com/vi/I9OyZfUXhII/maxresdefault.jpg",
    image4: "http://www.extravaganzi.com/wp-content/uploads/2009/12/Porsche-9ff-GT9-R-5.jpg",
    image5: "http://gtspirit.com/wp-content/uploads/2011/09/9ff-GT9-R.jpg",
    image6: "http://image.superstreetonline.com/f/33681082+w+h+q80+re0+cr1/epcp-1109-02-o%2B9ff-gt9-r-911-turbo%2Bdriver-side-rear-quarter-view",
    image7: "https://i.pinimg.com/736x/1c/c8/4f/1cc84f917385562b26432a664b628e2c--series-racing.jpg",
    image8: "http://image.superstreetonline.com/f/33681106+w+h+q80+re0+cr1/epcp-1109-10-o%2B9ff-gt9-r-911-turbo%2Binterior",
    image9: "http://image.superstreetonline.com/f/36163317+w+h+q80+re0+cr1/epcp_1105_05_z%2Bporsche_9ff_speed9%2Binterior_view.jpg",
    type : "4.0L 1,120 bhp (835 kW; 1,136 PS) hp B6 twin-turbo (GT9-R)",
    displacement : "4.0 l (244 ci)",
    borexstroke : "--",
    compression : "--",
    maxpower : "1,120 bhp (840 kW; 1,140 PS)",
    maxtorque : "1050 Nm (774 lb-ft)",
    transmissiontype : "6-speed Manual",
    gearbox :"6-speed Manual",
    maxspeed :  "420 km/h (260 mph)",
    acceleration :"0–100 km/h (62 mph) in 2.9s",
    rimf :"--",
    rimr : "--",
    tiref : "235/35/19",
    tirer :"325/30/19",
  },


  {
    name: "SSC_Ultimate_aero_",
    image: "https://images4.alphacoders.com/187/thumb-1920-187228.jpg",
    description: "<h2></h2><p>The company formerly known as Shelby Super Cars, now known as SSC, has already released the replacement for its extreme supercar, the Ultimate Aero. This replacement car is dubbed the Tuatara. You didn’t think that SSC would let its one-multiple-world-record-holding supercar just ride away into the sunset, did you?</p>",
    description1:"<h2></h2><p>If you did, you’re mistaken, as SSC has just announced a special edition model of the Ultimate Aero, dubbed the Ultimate Aero XT, which boasts a power plant never before seen in an Ultimate Aero and styling to match the might behind the seats.</p>",
    image1: "https://i.ytimg.com/vi/GJKGDQsgpVw/maxresdefault.jpg",
    image2: "https://www.walldevil.com/wallpapers/a36/ssc-ssc-ultimate-aero-shelby-supercars.jpg",
    image3: "http://www.juniorcardesigner.com/wp-content/uploads/2013/10/SSC-Ultimate-Aero-TT-19.jpg",
    image4: "https://www.desktopbackground.org/p/2012/12/11/497425_hd-red-ssc-ultimate-aero-supercar-wallpaper-jpg_1920x1230_h.jpg",
    image5: "http://3.bp.blogspot.com/-Vfxk5fCL2VA/UIBMBMMUMCI/AAAAAAAAA_o/aejkShYZQq4/s1600/shelby-supercars-ultimate-aero-08.jpg",
    image6: "http://files.all-free-download.com//downloadfiles/wallpapers/1920_1080/ssc_ultimate_aero_wallpaper_other_cars_2304.jpg",
    image7: "https://s-media-cache-ak0.pinimg.com/originals/6d/7f/30/6d7f30ae069409d32b327e7ca777aa5e.jpg",
    image8: "https://i.ytimg.com/vi/vHgMs46RTic/maxresdefault.jpg",
    image9: "https://s-media-cache-ak0.pinimg.com/originals/b7/9e/d0/b79ed085e4977e5476dfee5e67277aef.jpg",
    type : "V8",
    displacement : "6800cc",
    borexstroke : "",
    compression : "",
    maxpower : "1300 @ 6800 ",
    maxtorque : "1004 @ 6800 ",
    transmissiontype : "7-SpeedTriple Clutch ",
    gearbox :"7-SpeedTriple Clutch ",
    maxspeed :  "273 mph",
    acceleration :"2.65 sec. ",
    rimf :"",
    rimr : "",
    tiref : "",
    tirer :"",
  },


  {
    name: "Audi_R8_",
    image: "https://wallpapercave.com/wp/qzaGTTR.jpg",
    description: "<h2>A legendary race car to own</h2><p>Sharing just under 50% of the same parts as the R8 GT3 LMS race car, the Audi R8 Coupe is bred through the lens of motorsport. The 540-hp or 610-hp V10 plus engine epitomizes the mid-engine drivetrain concept, providing ideal vehicle balance through its center of gravity and dynamic weight transfer characteristics. </p>",
    description1:"<h2>quattro® all-wheel drive</h2><p>ro®, which emulates a rear-wheel drive vehicle, but with the ability to send up to 100% of available torque to the front axle, depending on the driving situation. This is made possible by advanced technologies, like the electronically controlled hydraulic multi-plate clutch, the addition of torque vectoring and quattro® integration within the Audi drive select system.</p>",
    image1: "http://7wallpapers.net/wp-content/uploads/6_Audi-R8-wallpaper.jpg",
    image2: "http://www.hdcarwallpapers.com/walls/audi_r8_hd_widescreen-wide.jpg",
    image3: "http://www.hdcarwallpapers.com/walls/2013_audi_r8-wide.jpg",
    image4: "https://www.hdwallpapers.in/walls/2010_audi_r8_lms-wide.jpg",
    image5: "http://images.caricos.com/a/audi/2013_audi_r8/images/1920x1080/2013_audi_r8_31_1920x1080.jpg",
    image6: "http://blog.hdwallsource.com/wp-content/uploads/2016/01/awesome-2015-audi-r8-wallpaper-46505-47883-hd-wallpapers.jpg",
    image7: "http://images.caricos.com/a/audi/2017_audi_r8_v10_spyder/images/2560x1440/2017_audi_r8_v10_spyder_36_2560x1440.jpg",
    image8: "http://images.caricos.com/a/audi/2016_audi_r8_v10_plus/images/1920x1080/2016_audi_r8_v10_plus_20_1920x1080.jpg",
    image9: "http://www.moibbk.com/images/audi-r8-interior-2.jpg",
    type : "5.2-liter V10 FSI® engine",
    displacement : "5,204",
    borexstroke : "84.5 x 92.8",
    compression : "--",
    maxpower : "610 @ 8,250",
    maxtorque : "413 @ 6,500",
    transmissiontype : "Seven-speed S tronic® dual-clutch transmission and quattro® all-wheel drive",
    gearbox :"7 speed dual-clutch",
    maxspeed :  "199 mph9",
    acceleration :"Acceleration (0 – 60 mph)3.2 seconds",
    rimf :"--",
    rimr : "--",
    tiref : "--",
    tirer :"--",
  },


  {
    name: "Lexus_lc",
    image: "https://www.hdwallpapers.in/walls/lexus_lc_500_4k-HD.jpg",
    description: "<h2>Overall handling Performance equal to the Aston Martin DB11*</h2><p>Experience a world-class prestige luxury coupe and a new era of uncompromising design and performance. An all-new platform, 471 horsepower* and a class-leading 10-speed automatic transmission come together to create our most responsive vehicle yet.</p>",
    description1:"<h2></h2><p></p>",
    image1: "https://www.lexus.com/cm-img/gallery/2018/LC/Lexus-LC-ultra-white-gallery-overlay-1204x677-LEX-LCH-MY18-0003-02.jpg",
    image2: "http://images.caricos.com/l/lexus/2012_lexus_lf-lc_blue_concept/images/1920x1080/2012_lexus_lf-lc_blue_concept_4_1920x1080.jpg",
    image3: "http://www.hdcarwallpapers.com/walls/lexus_lc_500_new_york_auto_show_2-HD.jpg",
    image4: "http://images.caricos.com/l/lexus/2017_lexus_lc_500/images/1920x1080/2017_lexus_lc_500_1_1920x1080.jpg",
    image5: "https://d3rvezpmgp265q.cloudfront.net/lexusone/lexgbenv11/2017-lexus-lc-gallery-014-exterior-1920x1080_tcm-3157-1028383.jpg",
    image6: "http://st.automobilemag.com/uploads/sites/11/2016/01/2018-Lexus-LC-500-side-side-profile-02.jpg",
    image7: "http://dzag5wgsqu6mr.cloudfront.net/wp-content/uploads/2017/03/Lexus-LC-interior-09.jpg",
    image8: "http://st.motortrend.com/uploads/sites/5/2017/04/2018-Lexus-LC-500-interior-overview.jpg",
    image9: "http://images.caricos.com/l/lexus/2017_lexus_lc_500/images/2560x1440/2017_lexus_lc_500_42_2560x1440.jpg",
    type : "V8",
    displacement : "5.0 L",
    borexstroke : "--",
    compression : "12.3 : 1",
    maxpower : "471 horsepower",
    maxtorque : "398 @ 4,800",
    transmissiontype : "10-speed electronically controlled Direct-Shift transmission with magnesium paddle shifters",
    gearbox :"10-speed electronically controlled Direct-Shift",
    maxspeed :  "168 TOP TRACK SPEED (MPH)*",
    acceleration :"4.4s 0–60 MPH (SEC)*",
    rimf :"--",
    rimr : "--",
    tiref : "--",
    tirer :"--",
  },


  {
    name: "Porsche_Boxter_",
    image: "http://www.firsthdwallpapers.com/uploads/2013/07/porsche-boxster-s-2013-hd-3-590x331-porsche-boxster-s.jpg",
    description: "<h2></h2><p>Porsche's smallest sportscar twin, the Boxster and the Cayman have got a new name that binds them together – the Porsche 718. Just like before, the drop-top roadster will be called the 718 Boxster while the hardtop coupe will be called the Cayman. The Le Mans winning 718 moniker has been revived after five decades</p>",
    description1:"<h2></h2><p></p>",
    image1: "https://i.ytimg.com/vi/1iy7cvzg6Ec/maxresdefault.jpg",
    image2: "http://st.motortrend.com/uploads/sites/10/2015/09/2016-Porsche-Boxster-Spyder-front-three-quarter1.jpg?interpolation=lanczos-none&fit=around|640:425",
    image3: "http://1.bp.blogspot.com/-TgBF_JbMQEk/U9HnjDjLodI/AAAAAAAAAkQ/hn_fg4nmRg4/s1600/2014-porsche-boxster-photo.jpg",
    image4: "http://cdntdreditorials.azureedge.net/cache/d/2/9/7/5/7/d29757a6c147ed8cbfe159924d37d4a1a4c83a8e.jpg",
    image5: "http://images.caricos.com/p/porsche/2016_porsche_boxster_spyder/images/1920x1080/2016_porsche_boxster_spyder_16_1920x1080.jpg",
    image6: "http://images.caricos.com/p/porsche/2017_porsche_718_boxster/images/2560x1440/2017_porsche_718_boxster_10_2560x1440.jpg",
    image7: "http://images.caricos.com/t/techart/2013_techart_porsche_boxster/images/1920x1080/2013_techart_porsche_boxster_7_1920x1080.jpg",
    image8: "http://media.caranddriver.com/images/12q1/436883/2013-porsche-boxster-s-interior-photo-445911-s-1280x782.jpg",
    image9: "https://d1evvto86t5vms.cloudfront.net/news/wp-content/uploads/images/2013/01/Boxster-S.jpg",
    type : "2.0 L 4-cylinder",
    displacement : "1,988 cm³ 	",
    borexstroke : "-",
    compression : "--",
    maxpower : "300 PS 	",
    maxtorque : "380 Nm 	",
    transmissiontype : "Rear-wheel drive 	",
    gearbox :"6-speed with dual-mass flywheel, self-adjusting clutch",
    maxspeed :  "275 km/h 	",
    acceleration :" 0 - 100 km/h -5.1 s ",
    rimf :"8 J x 18 ET 57 	",
    rimr : "9,5 J x 18 ET 49",
    tiref : "235/45 ZR 18 	",
    tirer :"265/45 ZR 18 	",
  },

  {
    name: "Chevrolet_Corvette_z06_",
    image: "https://www.hdwallpapers.in/walls/chevrolet_corvette_z06_2015-wide.jpg",
    description: "<h2>Its competitors are few </h2><p>Z06 is singular in its focus of challenging the greatest supercars in the world. Developed in tandem with the C7.R race car and offering 650 horsepower and 650 lb.-ft. of torque, Z06 is the supercar they never saw coming.</p>",
    description1:"<h2></h2><p>Z06 and the C7.R race car were codeveloped and share many features and components. With Stingray as their foundation, Z06 and C7.R were engineered to dominate the racing competition.</p>",
    image1: "https://www.hdwallpapers.in/walls/chevrolet_corvette_z06_convertible_2015-wide.jpg",
    image2: "https://www.carpixel.net/w/2f47f72fdee3343d62547cd54fbf1962/chevrolet-corvette-z06-wallpaper-hd-15342.jpg",
    image3: "http://fullhdpictures.com/wp-content/uploads/2016/05/Beautiful-Chevrolet-Corvette-Z06-Wallpaper.jpg",
    image4: "http://images.caricos.com/c/chevrolet/2015_chevrolet_corvette_z06/images/1920x1080/2015_chevrolet_corvette_z06_116_1920x1080.jpg",
    image5: "http://www.hdcarwallpapers.com/walls/2017_chevrolet_corvette_grand_sport-wide.jpg",
    image6: "http://hqpictures.net/wp-content/uploads/2015/07/Chevrolet-Corvette-Z06-Desktop.jpg",
    image7: "http://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2018/performance/corvette-z06/mov/01-images/2018-corvette-z06-shared13.jpg?imwidth=650",
    image8: "http://xdesktopwallpapers.com/wp-content/uploads/2011/11-1/2012-Chevrolet-Centennial-Edition-Corvette-Z06-Interior.jpg",
    image9: "http://st.automobilemag.com/uploads/sites/11/2015/07/2015-Chevrolet-Corvette-Z06-Convertible-interior-details.jpg",
    type : "SUPERCHARGED 6.2L V8 ENGINE ",
    displacement : "6.2L/376",
    borexstroke : "--",
    compression : "--",
    maxpower : "650 HORSEPOWER ",
    maxtorque : "650 LB.-FT. OF MAX TORQUE ",
    transmissiontype : "Transmission, 7-speed manual",
    gearbox :"Transmission, 7-speed manual",
    maxspeed :  "205 mph",
    acceleration :"0 TO 60 IN 2.95 SECONDS",
    rimf :"19 front Pearl Nickel-painted aluminum Z06® wheels with summer-only tires",
    rimr : "20 rear, Pearl Nickel-painted aluminum Z06® wheels with summer-only tires",
    tiref : "19 front",
    tirer :"20 rear",
  },

  {
    name: "Mercedes_Benz_Sl_",
    image: "http://2.bp.blogspot.com/-8sOH3OkPqQY/UTAXDDFh0KI/AAAAAAAAAUo/FcDTVotfnGk/s1600/2013-mercedes-benz-sl-class-hd-widescreen-desktop-wallpaper-background-1920px_07.jpg",
    description: "<h2>Power That Takes Control.</h2><p>With the Mercedes-AMG SL 63 and the Mercedes-AMG SL 65, we are underscoring once more our determination to make the most of everything — every moment, every meter. Enjoy the thrill of the outstanding power delivery and exceptional dynamics of thoroughbred sports cars that make it perfectly clear, even at a standstill, what they were made for — Driving Performance.</p>",
    description1:"<h2>Universal Talent. </h2><p>In the combination of bends and straights, the Mercedes-AMG SL 63 unfurls its full potential. The AMG SPEEDSHIFT MCT 7-speed sports transmission with double-declutch function works together with the AMG sports suspension with Active Body Control for perfect power delivery in all situations. The interaction of the two enables rapid gear shifting and, through the choice of drive programs, an impressive bandwidth between sporty and comfortable. The rear-axle differential lock is perfectly tuned to match, for even more traction, especially when accelerating out of bends.</p>",
    image1: "http://images.caricos.com/m/mercedes-benz/2013_mercedes-benz_sl-class/images/1920x1080/2013_mercedes-benz_sl-class_67_1920x1080.jpg",
    image2: "http://hqpictures.net/wp-content/uploads/2015/09/Mercedes-Benz-SL-Class-Wallpaper-HD.jpg",
    image3: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Mercedes-Benz_SL_350_%28R_231%29_%E2%80%93_Frontansicht_ge%C3%B6ffnet_%281%29%2C_22._Mai_2013%2C_D%C3%BCsseldorf.jpg/1200px-Mercedes-Benz_SL_350_%28R_231%29_%E2%80%93_Frontansicht_ge%C3%B6ffnet_%281%29%2C_22._Mai_2013%2C_D%C3%BCsseldorf.jpg",
    image4: "http://st.motortrend.com/uploads/sites/10/2016/09/2017-mercedes-benz-sl-450-convertible-rear-view.png",
    image5: "https://a.tcimg.net/vehicle-images/inventory/49685/83/22/WDDJK6FA2FF032283/RVW7ILDKKTT4U5YFARVIX33ARA-600.jpg?idx=0",
    image6: "https://www.carpixel.net/w/c5851c32b1e3b10fd42aed21df0c4323/mercedes-benz-sl-class-amg-styling-wallpaper-hd-52803.jpg",
    image7: "https://cars.usnews.com/static/images/Auto/izmo/i44062347/2018_mercedes_benz_sl_roadster_dashboard.jpg",
    image8: "http://www.moibbk.com/images/mercedesbenz-slclass-interior-4.jpg",
    image9: "http://st.motortrend.com/uploads/sites/10/2015/11/2016-mercedes-benz-sl-class-63-amg-convertible-engine.png",
    type : "AMG 5.5-liter V8 biturbo engine",
    displacement : " 4.7 liters",
    borexstroke : "--",
    compression : "--",
    maxpower : " 20 horsepower",
    maxtorque : "449 hp and 516 lb-ft",
    transmissiontype : "7-speed automatic, ",
    gearbox :"7-speed automatic, ",
    maxspeed :  "130 mph.",
    acceleration :" 60 mph in the mid 4-second range",
    rimf :"--",
    rimr : "--",
    tiref : "--",
    tirer :"--",
  },

  {
    name: "Acura_NSX_",
    image: "http://www.hdcarwallpapers.com/walls/2017_acura_nsx_geneva_motor_show-HD.jpg",
    description: "<h2>Building a Vision </h2><p>Equal parts rational and emotional, sports car engineering is at its best when the tension between these sides results in harmony. Such was the vision for NSX: power and beauty, precision and nuance, interwoven such that the car itself becomes both a machine and an experience.</p>",
    description1:"<h2>PRECISE PHILOSOPHY</h2><p>Precision crafted performance, the Acura mantra, served as both philosophical approach and physical benchmark for NSX. Thus a wholly new supercar was brought to life: an exotic sports car born of racing DNA, equal parts adrenaline and composure.</p>",
    image1: "http://www.hdcarwallpapers.com/walls/honda_acura_nsx_4k-HD.jpg",
    image2: "https://www.carpixel.net/w/686e660c56b2e54c3a322411d56f11cf/acura-nsx-wallpaper-hd-32260.jpg",
    image3: "http://www.hdcarwallpapers.com/walls/2013_acura_nsx_concept_3-wide.jpg",
    image4: "http://www.hdcarwallpapers.com/walls/2016_acura_nsx_technical-HD.jpg",
    image5: "https://s-media-cache-ak0.pinimg.com/originals/7d/00/30/7d00301908253f69f3e8c53a7b66ce6a.jpg",
    image6: "http://images.caricos.com/a/acura/2016_acura_nsx/images/1920x1080/2016_acura_nsx_9_1920x1080.jpg",
    image7: "https://www.networm.org/wp-content/uploads/2015/11/acura-nsx-concept-interior-photo-497780-s-1280x782.jpg",
    image8: "http://st.motortrend.com/uploads/sites/5/2015/10/2017-Acura-NSX-engine.jpg",
    image9: "http://www.autoguide.com/blog/wp-content/uploads/2015/10/2017-acura-nsx-lowest-center-of-gravity.jpg",
    type : "5-degree, 3.5-liter DOHC V-6 engine ",
    displacement : "3.5 liter",
    borexstroke : "--",
    compression : "10.0:1",
    maxpower : "500-HP",
    maxtorque : "406 lb.-ft.",
    transmissiontype : "The race-ready 9-speed DCT ",
    gearbox :"double-cone synchronizers and electronic shift actuator",
    maxspeed :  "191 MPH.",
    acceleration :"0 – 60 MPH in 2.7 seconds",
    rimf :"--",
    rimr : "--",
    tiref : "205/50R15",
    tirer :" 225/50R16",
  },

]

function seedDB(){

  //remove all campgrounds
Campground.remove({},function(err){
  if(err){
    console.log(err);
  }
  console.log("removed");
  //add campgrounds
  data.forEach(function(seed){
    Campground.create(seed,function (err,campground) {
      if(err){
        console.log(err);
      }else{
        console.log("added cars");
        //create a comment

      }
    });
  });
  });
}



module.exports = seedDB;
